### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by stephanpelikan** [camunda-community-hub/vanillabp-camunda8-adapter#1]
Please push this version to Maven-Central.

The staging-repo reference is: *orgcamunda-2195*

Thx,
Stephan

**Comment by stephanpelikan** [comment]
Sorry, forgot to add the @camunda-community-hub/devrel reference.

**Comment by NPDeehan** [comment]
Hi @stephanpelikan 
I've kicked off the release.

**Comment by stephanpelikan** [comment]
Thank you @NPDeehan for jumping in! It is already published to Maven-Central 👍
